apiVersion: v2
name: hive-metastore
description: A Helm chart for Hive Standalone Metastore
type: application
version: 0.1.1
appVersion: "3.0.0"
dependencies:
  - name: postgresql
    version: 10.15.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
